import React from 'react'

function Mylazypage() {
  return (
    <div className='container'>
        <div className='row'>
            <div className='12'>
                <p>load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.load: A function that returns a Promise or another thenable (a Promise-like object with a then method). React will not call load until the first time you attempt to render the returned component. After React first calls load, it will wait for it to resolve, and then render the resolved value’s .default as a React component. Both the returned Promise and the Promise’s resolved value will be cached, so React will not call load more than once. If the Promise rejects, React will throw the rejection reason for the nearest Error Boundary to handle.
Returns 
lazy returns a React component you can render in your tree. While the code for the lazy component is still loading, attempting to render it will suspend. Use  to display a loading indicator while loading.</p>


            </div>
        </div>
    </div>
  )
}

export default Mylazypage